### PR TITLE
Add sync button to other flux objects

### PR DESCRIPTION
**Pull request by jpellizzari**
Adds sync buttons to the Sources and HelmReleases page:
Screenshot from 2021-05-12 12-28-39

The `clustersserver.go` file is getting busy, but organizing it would have made this PR harder to review, so I will save that for later.

### CODE REVIEW

**Comment by stefanprodan** [comment]
@jpellizzari I see that the API packages are very old, what will happen is that when people click on the sync button, all the new fields that we've added to Flux APIs will be removed, imagine someone uses Azure and they've set the git implementation to libgit2, then they click the sync button, the UI will remove that field crashing the whole setup without any chance of recovery...

**Comment by jpellizzari** [comment]
> @jpellizzari I see that the API packages are very old, what will happen is that when people click on the sync button, all the new fields that we've added to Flux APIs will be removed, imagine someone uses Azure and they've set the git implementation to libgit2, then they click the sync button, the UI will remove that field crashing the whole setup without any chance of recovery...

I assume that just means updating the versions to the `go.mod` will resolve that issue in this case. Should we add some automation on upgrading those dependencies? A check in CI would probably be a good way to go, maybe during the "release" job.

**Comment by stefanprodan** [comment]
@jpellizzari yes we need to keep the UI in-sync with flux2 release, in the same way we do for terraform provider. Some examples:
- https://github.com/fluxcd/flux2/blob/main/.github/workflows/update.yaml
- https://github.com/fluxcd/terraform-provider-flux/blob/main/.github/workflows/update.yaml

**Comment by stefanprodan** [comment]
For this PR, please use the packages from here https://github.com/fluxcd/flux2/blob/v0.13.4/go.mod on the long run we need to automate the go.mod updates and release the UI after each flux2 release.

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @jpellizzari

**Pull request merged**
