### PR TITLE
Add graph visualization

### PR DESCRIPTION
**Pull request by jpellizzari**
Adds a basic graph viz of the Reconciliation "tree" for a Kustomization:

Screenshot from 2021-06-02 10-09-56

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @jpellizzari ☕

**Comment by squaremo** [comment]
Very smart looking!
I think it is worth distinguishing between the relationships "this object synced that object" as in a Kustomization->Deployment, and "this object is the owner of that object" as in Deployment->ReplicaSet. In terms of what we're trying to show the user, there's two different things going on: firstly, how syncs are configured, and secondly, what the outcome of a sync is. In the example, the first is represented by the sole kustomization object, but you can easily imagine a chain of "this kustomization synced that kustomization which synced this deployment ...."

**Comment by jpellizzari** [comment]
> I think it is worth distinguishing between the relationships "this object synced that object" as in a Kustomization->Deployment, and "this object is the owner of that object" as in Deployment->ReplicaSet. In terms of what we're trying to show the user, there's two different things going on: firstly, how syncs are configured, and secondly, what the outcome of a sync is. In the example, the first is represented by the sole kustomization object, but you can easily imagine a chain of "this kustomization synced that kustomization which synced this deployment ...."

Good point. I think color or possibly some sort of treatment on the lines would be a good way to communicate that. @bia any thoughts?

**Comment by bia** [comment]
@jpellizzari @squaremo 
I think "this object is the owner of that object" should be the visually strongest relationship to display, so we keep the solid line/arrow for those. In the case of "this kustomization synced that kustomization which synced this deployment" I could imagine a coloured (shades of blue ?) line persisting through that chain. Is that possible ?

**Comment by jpellizzari** [comment]
I have captured feedback in a follow-up issue here: https://github.com/fluxcd/webui/issues/48

**Comment by jpellizzari** [comment]
It should also be noted that this graph starts to get untenable with large groups of reconciled objects. Here is the `flux-system` kustomization for example:

Screenshot from 2021-06-03 09-18-55

**Pull request merged**
