### PR TITLE
Add more flux components

### PR DESCRIPTION
**Pull request by adberger**
- Update Source Controller from `v0.13.2` to `v0.17.2`
- Add the following flux components:
  - Alert (Notification Controller)
  - Provider (Notification Controller)
  - Receiver (Notification Controller)
  - Image Policy (Image Reflector Controller)
  - Image Repository (Image Reflector Controller)
  - Image Update Automation (Image Automation Controller)

### CODE REVIEW

**Comment by adberger** [comment]
I currently get the following error for every reference of the enum Type in `ui/lib/rpc/clusters.ts` and I don't know why:
type

I did `make proto` after my changes to the `pkg/rpc/clusters/clusters.proto` file

**Comment by juozasg** [comment]
@adberger The PR looks good, I will try to fix your issue today and report.

**Comment by juozasg** [comment]
It appears this error is caused by referring to a .proto Enum `Source.Type` in the generated TypeScript definition. It looks like protoc twirp plugin is not translating nested types from protobuff sources. You can see in the previously generated code that `string` is used instead of `Type`: https://github.com/fluxcd/webui/blob/main/ui/lib/rpc/clusters.ts

```
export interface Kustomization {
...
  sourcerefkind?: string;
...
}
```

I wonder why that changed? Can you please try `make proto` on fluxcd:main and see which output you get? Could it be caused by changes to [github.com/twitchtv/twirp/protoc-gen-twirp](https://github.com/larrymyers/protoc-gen-twirp_typescript)?

Could have been this commit that added exported enums but probably not support for nested enums: https://github.com/larrymyers/protoc-gen-twirp_typescript/commit/6811d8700f0a53ed840152bebff1b70137fa367e

I'm currently working on a fork of webui that will eliminate the twirp protobuff layer and replace it with server-side rendering to simplify the codebase.  It should have feature parity with the changes you are including here, so I want to merge it and take advantage of your contributions, but not invest too much time into maintaining the twirp protobuff integration.

**Comment by adberger** [comment]
> 

When I'm running `make proto` on fluxcd:main I get the same errors now. So your assumption seems to be correct.
But I'm not exactly sure how to fix this before merging?
webui is using _twirp v7.1.0+incompatible_ and https://github.com/larrymyers/protoc-gen-twirp_typescript seems to be for v5 and partially v6. Could that be a problem (too)?

**Comment by adberger** [comment]
When I manually add:
```
export enum Type {
    Git = 0,
    Bucket = 1,
    Helm = 2,
    Chart = 3
}
```
the errors are gone. So it looks like at least https://github.com/larrymyers/protoc-gen-twirp_typescript/pull/63/files#diff-fa88ce5178e5c62aa114604879ceb9b25f69b78b4fcde863ec6860d0f0a76b4cR19-R26 isn't doing what it's intended to do.

**Comment by adberger** [comment]
@juozasg I think I've fixed the problem with the latest commit.

On a side note: I didn't implemented any tests for my changes yet.

**Pull request closed without merging**
