### PR TITLE
Add events page

### PR DESCRIPTION
**Pull request by jpellizzari**
Adds a basic events page to help with troubleshooting.

Screenshot from 2021-03-12 14-08-22

### CODE REVIEW

**Review by bia — COMMENTED** [review]
This is helpful!
Thought some of these 'Reason's don't semantically fit the category name 'Reason'?
Screenshot 2021-03-13 at 22 37 48

Also, this may be user error, but this branch for some reason has trouble fetching Contexts for me : 
Screenshot 2021-03-13 at 22 34 32

**Comment by jpellizzari** [comment]
> This is helpful!
> Thought some of these 'Reason's don't semantically fit the category name 'Reason'?

Not sure what's going on with that. That is what the API response returns.

**Comment by bia** [comment]
>Not sure what's going on with that. That is what the API response returns.

I understand, but in that case should the column be titled 'Reason' or something else like  'Type'?

**Comment by hiddeco** [comment]
This needs to be normalized from our point to meet the K8s standards, see: https://github.com/fluxcd/pkg/pull/56#discussion_r531236806

**Comment by jpellizzari** [comment]
> > Not sure what's going on with that. That is what the API response returns.
> 
> I understand, but in that case should the column be titled 'Reason' or something else like 'Type'?

There is another field called "type", and the "Reason" field is returning those "LeaderElection" values. I think @hiddeco 's comment speaks to that discrepancy

**Comment by jpellizzari** [comment]
> This needs to be normalized from our point (as in: the controllers that emit the events) to meet the K8s standards, see: [fluxcd/pkg#56 (comment)](https://github.com/fluxcd/pkg/pull/56#discussion_r531236806)

Is there something I need to change in this PR?

**Comment by hiddeco** [comment]
No, nothing to be done here. We need to address this in `fluxcd/pkg` and implement it in the controllers, once that's done it will show up correctly and make sense again in the UI.

**Pull request merged**
