### PR TITLE
Relocate top navigation event handling outside of the view

### PR DESCRIPTION
**Pull request by adberger**
Cherry picked from https://github.com/fluxcd/webui/pull/57:
- Relocate top navigation event handling outside of the view
- Some formatting changes
- Some spelling changes

### CODE REVIEW

**Comment by stefanprodan** [comment]
@adberger that you for this PR. We decided to wait with the Go 1.17 upgrade until our upstream dependencies (controller-runtime, helm, kstatus, etc) are aligned. Please see: https://github.com/fluxcd/flux2/issues/2016

**Comment by adberger** [comment]
@stefanprodan Is there a reason to do this, even if it works for this project?  
Just asking out of curiosity

**Comment by stefanprodan** [comment]
> Is there a reason to do this, even if it works for this project?

Yes we want to have an homogeneous build system, using Go 1.17 in webui that consumes various Flux packages that are pinned on Go 1.16 is not desirable.

**Comment by adberger** [comment]
> > Is there a reason to do this, even if it works for this project?
> 
> Yes we want to have an homogeneous build system, using Go 1.17 in webui that consumes various Flux packages that are pinned on Go 1.16 is not desirable.

Okay then, I removed the upgrade to go version 1.17

**Comment by adberger** [comment]
@kingdonb can you take a look at it?

**Comment by juozasg** [comment]
@adberger LGTM. However, can you please update the PR to have a more detailed description of what it contains: fixes context names being replaced with cluster names in the context selector dropdown, refactors context selector changed event, etc. 

@stefanprodan This works and should be merged

**Comment by adberger** [comment]
@juozasg Thanks for your comment. The context dropdown bug was already fixed and merged, see #59 
But I changed the title & description of this PR, so I hope this is good now.

**Comment by stefanprodan** [comment]
@adberger please rebase with upstream main and force push.

**Comment by adberger** [comment]
@stefanprodan Is this way (merge from main into this branch) ok too?

**Pull request closed without merging**
