### PR TITLE
Upgrade nodejs

### PR DESCRIPTION
**Pull request by adberger**
- Update nodejs from `14.15.1` to `v16.x.x`

### CODE REVIEW

**Comment by adberger** [comment]
@kingdonb can you take a look at it?

**Review by stefanprodan — COMMENTED** [review]
Please update the version in CI https://github.com/fluxcd/webui/blob/main/.github/workflows/main.yaml#L13

**Comment by adberger** [comment]
@stefanprodan currently the versions which are supported by https://github.com/actions/setup-node are up to 16.13.0.
Should I change to 16.x.x instead of 17.0.1 because 16 is a LTS version?

**Comment by stefanprodan** [comment]
> Should I change to 16.x.x instead of 17.0.1 because 16 is a LTS version?

Yes please

**Comment by adberger** [comment]
@stefanprodan could you review again?

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @adberger

**Pull request merged**
