### PR TITLE
Post notice about the project being on hold

### PR DESCRIPTION
**Pull request by squaremo**
@bia @jpellizzari I've requested reviews from you both, as the maintainers; please check you're happy with the words and wording.

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]

**Review by jpellizzari — APPROVED** [review]

**Comment by kingdonb** [comment]
Please hold, we are discussing this at the DX meeting. More information soon

**Comment by kingdonb** [comment]
We happily announced today, in the Flux Dev meeting, we have secured the help of @juozasg to work on maintaining the fluxcd/webui project. I'm helping bring them up to speed this week, and we should see more contributions coming soon!

**Comment by squaremo** [comment]
I've added a few words to recognise Juozas' involvement.

**Comment by squaremo** [comment]
@bia Sorry to drag you back once again -- it'd be good to have your sign-off here too.

**Review by bia — APPROVED** [review]
Yep! Thanks for the ping @squaremo

**Pull request merged**
